[target.x86_64-unknown-linux-musl]
pre-build = [
  "apt-get update",
  "apt-get install -y --no-install-recommends pkg-config libdbus-1-dev",
  "echo '#!/bin/sh' > /usr/local/bin/pkg-config",
  "echo 'PKG_CONFIG_ALLOW_CROSS=1 exec /usr/bin/pkg-config \"$@\"' >> /usr/local/bin/pkg-config",
  "chmod +x /usr/local/bin/pkg-config"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
  "dpkg --add-architecture arm64",
  "apt-get update",
  "apt-get install -y --no-install-recommends pkg-config libdbus-1-dev:arm64",
  "echo '#!/bin/sh' > /usr/local/bin/pkg-config",
  "echo 'PKG_CONFIG_ALLOW_CROSS=1 exec /usr/bin/pkg-config \"$@\"' >> /usr/local/bin/pkg-config",
  "chmod +x /usr/local/bin/pkg-config"
]

[target.armv7-unknown-linux-musleabihf]
pre-build = [
  "dpkg --add-architecture armhf",
  "apt-get update",
  "apt-get install -y --no-install-recommends pkg-config libdbus-1-dev:armhf",
  "echo '#!/bin/sh' > /usr/local/bin/pkg-config",
  "echo 'PKG_CONFIG_ALLOW_CROSS=1 exec /usr/bin/pkg-config \"$@\"' >> /usr/local/bin/pkg-config",
  "chmod +x /usr/local/bin/pkg-config"
]
